name: Build and Save Docker Artifacts

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container

      - name: Create cache directory
        run: mkdir -p /tmp/.buildx-cache

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: List directory contents for debugging
        run: |
          ls -R

      - name: Copy Dockerfile
        run: mkdir -p /tmp/docker && cp googom/.devcontainer/Dockerfile /tmp/docker/Dockerfile

      - name: Build Docker image
        run: |
          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --tag my-docker-image --file /tmp/docker/Dockerfile --load .

      - name: Save Docker image as a tarball
        run: |
          docker save my-docker-image -o my-docker-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-docker-image
          path: my-docker-image.tar
